core/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path,include, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.views import static as ds

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from core.views import LoginView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('registration.backends.simple.urls')),
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    #path('usuarios/create_user', CreateUserView.as_view(), name='create_user'),
    path('usuarios/',include('usuarios.urls')),
    path('', views.home1, name='home1'),
    path('todolist/',include('todolist.urls')),
    path('agendaFinanceira/',include('agendaFinanceira.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),  # URL para obter um token de autenticação


    re_path(r'^prestador/', include(('usuarios.urls', 'usuarios'),namespace='usuarios')),
    re_path(r'^prestador/', include(('prestadores.urls','prestadores'),namespace='prestadores')),
    re_path(r'^select2/', include('django_select2.urls')),
     

    re_path(r'^media/(?P<path>.*)$', ds.serve,
            {'document_root': settings.MEDIA_ROOT, }, name="media"),
] 
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prestadores/urls.py
from django.urls import path
#from django.conf.urls import url,re_path
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('cadastro-prestador-pf', views.cadastro_prestador_pf, name='cadastro_prestador_pf'),
    path('cadastro/dados-pessoais', views.dados_pessoais, name='dados_pessoais'),
    path('cadastro/cadastros_list',views.cadastros_list, name='cadastros_list'),
    path('cadastro/sucesso', views.sucesso2, name='sucesso'),
    re_path('cadastro/(?P<pk>[0-9]+)/$',views.cadastro_enviado,name='cadastro_prestadorpf')
]

usuarios/urls.py
from django.urls import path,include, re_path
from . import views
from django.views import static as ds
from django.conf import settings
from django.conf.urls.static import static
from .views import create_user,editar_perfil,perfil

urlpatterns = [
    path('create_user/', create_user, name='create_user'),
    path('perfil', views.perfil, name="perfil_usuario"),
    path('perfil/editar', views.editar_perfil,name="editar_perfil"),

    re_path(r'^media/(?P<path>.*)$', ds.serve,
            {'document_root': settings.MEDIA_ROOT, }, name="media"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
#from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save

from core.helpers import validate_CPF

def foto_perfil_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.user.email, "perfil_"+filename)

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('endereço de email'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

STATUS_SEXO = (
    ('1:', 'MASCULINO'),
    ('2:', 'FEMININO'),
    ('3:', 'OUTROS VALORES'),
    
)
STATUS_TIPO = (
    ('1:', 'ADMINISTRADOR'),
    ('2:', 'CLIENTE'),
    ('3:', 'OUTROS'),
    
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    nm_completo = models.CharField(verbose_name="Nome Completo", max_length=100,null=True, blank=True)
    nr_cpf_cgc = models.CharField(verbose_name="CPF",max_length=11,null=True, blank=True,validators=[validate_CPF])
    foto_perfil = models.ImageField(upload_to=foto_perfil_directory_path, null=True, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=200, blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True,verbose_name="Observações")
    idade = models.IntegerField(null=True)
    sexo = models.CharField(max_length=20, choices=STATUS_SEXO, default='OUTROS VALORES')
    tipo_usuario = models.CharField(max_length=30, choices=STATUS_TIPO, default='CLIENTE')
    nrTelCelular = models.CharField(max_length=11, blank=True, null=True, verbose_name='Nº telefone celular')

    def __str__(self):
       return str(self.nm_completo)

    class Meta:
        verbose_name = "perfil"
        verbose_name_plural = "perfis"

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
post_save.connect(create_profile, sender=User)

usuarios/forms.py
from registration.forms import RegistrationForm, RegistrationFormUniqueEmail
from django import forms
from django.forms import ModelForm
#from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _

from django.utils.html import format_html #para colocar o link na msg de erro
from django.contrib.auth import get_user_model
from .models import UserProfile
from crispy_forms.helper import FormHelper
from django.contrib.auth.forms import UserCreationForm

from crispy_forms.layout import Submit, Layout, Div, Fieldset
UserModel = get_user_model
User = UserModel()



class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('email',)  # Apenas o campo 'email' é mantido no formulário de criação de usuário


class MyRegForm(RegistrationFormUniqueEmail):

    def __init__(self, *args, **kwargs):
        super(MyRegForm, self).__init__(*args, **kwargs)
        for fieldname in ['email', 'password1', 'password2']:
            self.fields[fieldname].help_text = None
        # msg = format_html("""Caso já esteja cadastro acesso <a href="/accounts/activation-resend">Reenvie</a>""")
        # self.add_error('email', msg)
    def clean_email(self):
        # try:
        #     User.objects.get(email=email)
        # except User.DoesNotExist:
        #     return email
        # raise forms.ValidationError("A user with that username already exists123.")

        # usuario=User.objects.get(email__iexact=self.cleaned_data['email'])
        # if usuario.is_active==False:
        #     msg = format_html("""Caso já esteja cadastro acesso <a href="/accounts/activation-resend">Reenvie</a>""")
        #     self.add_error('email', msg)
        if User.objects.filter(email__iexact=self.cleaned_data['email']):
            usuario = User.objects.get(email__iexact=self.cleaned_data['email'])
            if usuario.is_active == False:
                msg = format_html(
                    """Caso já esteja cadastro acesso <a href="/accounts/activation-resend">Reenvie</a>""")
                raise forms.ValidationError(msg)
            else:
                raise forms.ValidationError(_("Este endereço de e-mail já está em uso. Forneça um endereço de e-mail diferente."))
        return self.cleaned_data['email']

    # def clean_email(self):
    #     """
    #     Validate that the supplied email address is unique for the
    #     site.
    #
    #     """
    #     if User.objects.filter(email__iexact=self.cleaned_data['email']):
    #         raise forms.ValidationError(_("This email address is already in use. Please supply a different email address."))
    #     return self.cleaned_data['email']
class UserProfileForm(ModelForm):
    # def __init__(self, *args, **kwargs):
    #     super(UserProfileForm, self).__init__(*args, **kwargs)
    #     # If you pass FormHelper constructor a form instance
    #     # It builds a default layout with all its fields
    #     self.helper = FormHelper(self)
    #     self.helper.add_input(Submit('submit', 'Submit'))
    class Meta:
        model = UserProfile
        fields = ['nm_completo', 'nr_cpf_cgc','foto_perfil', 'observacoes', 'tipo_usuario', 'nrTelCelular']
        # exclude = ['user']

usuarios/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from .models import User, UserProfile
from django.contrib.auth import authenticate, login
from .forms import UserProfileForm,CustomUserCreationForm
from django.shortcuts import redirect

def create_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')  # ou para qualquer outra página
    else:
        form = CustomUserCreationForm()
    return render(request, 'usuarios/create_user.html', {'form': form})

@login_required
def perfil(request):
    try:
        user = request.user
    except User.DoesNotExist:
        return redirect('home')
    return render(request, 'usuarios/perfil.html', {'selecteduser': user})

@login_required
def editar_perfil(request):
    userprofile = UserProfile.objects.get(user=request.user.id)
    data = {'nm_completo': userprofile.nm_completo, 'nr_cpf_cgc': userprofile.nr_cpf_cgc,'foto_perfil':userprofile.foto_perfil}
    if request.method == "POST":
        form = UserProfileForm(request.POST, request.FILES,instance=userprofile)
        if form.is_valid():
            perfil = form.save(commit=False)
            perfil.user = request.user
            perfil.save()
    else:
        form = UserProfileForm(initial=data)
    return render(request, 'usuarios/editar_perfil.html', {
        'form': form
    })

usuarios/templates/usuarios - Copia/perfil - Copia.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <style>
.card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.title {
  color: grey;
  font-size: 18px;
}

button {
  border: none;
  outline: 0;
  display: inline-block;
  padding: 8px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

a {
  text-decoration: none;
  font-size: 22px;
  color: black;
}

button:hover, a:hover {
  opacity: 0.7;
}
</style>
</head>
<body>

<h2 style="text-align:center">TimeLine</h2>

<div class="card">
  <img src="\media\cuidados_paciente.jpg" alt="Optimus" style="width:100%">
  <h1>Optimus</h1>
  <p class="title">Historico, Evolução</p>
  <p>ROGTI</p>
  <div style="margin: 24px 0;">
    <a href="#"><i class="fa fa-dribbble"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
 </div>
 <p><button>Contact</button></p>
</div>

</body>
</html>

<style>
* {
    box-sizing: border-box;
}

body {
    background-color: #F7819F;
    font-family: Helvetica, sans-serif;
}

/* The actual timeline (the vertical ruler) */
.timeline {
    position: relative;
    max-width: 1200px;
    margin: 0 auto;
}

/* The actual timeline (the vertical ruler) */
.timeline::after {
    content: '';
    position: absolute;
    width: 12px;
    background-color: white;
    top: 0;
    bottom: 0;
    left: 50%;
    margin-left: -3px;
}

/* Container around content */
.container {
    padding: 10px 40px;
    position: relative;
    background-color: inherit;
    width: 50%;
}

/* The circles on the timeline */
.container::after {
    content: '';
    position: absolute;
    width: 35px;
    height: 35px;
    right: -17px;
    background-color: white;
    border: 4px solid #FF9F55;
    top: 20px;
    border-radius: 50%;
    z-index: 1;
}

/* Place the container to the left */
.left {
    left: 0;
}

/* Place the container to the right */
.right {
    left: 50%;
}

/* Add arrows to the left container (pointing right) */
.left::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    right: 30px;
    border: medium solid white;
    border-width: 10px 0 10px 10px;
    border-color: transparent transparent transparent white;
}

/* Add arrows to the right container (pointing left) */
.right::before {
    content: " ";
    height: 0;
    position: absolute;
    top: 22px;
    width: 0;
    z-index: 1;
    left: 30px;
    border: medium solid white;
    border-width: 10px 10px 10px 0;
    border-color: transparent white transparent transparent;
}

/* Fix the circle for containers on the right side */
.right::after {
    left: -16px;
}

/* The actual content */
.content {
    padding: 20px 30px;
    background-color: white;
    position: relative;
    border-radius: 6px;
}

/* Media queries - Responsive timeline on screens less than 600px wide */
@media screen and (max-width: 600px) {
  /* Place the timelime to the left */
  .timeline::after {
    left: 31px;
  }

  /* Full-width containers */
  .container {
    width: 100%;
    padding-left: 70px;
    padding-right: 25px;
  }

  /* Make sure that all arrows are pointing leftwards */
  .container::before {
    left: 60px;
    border: medium solid white;
    border-width: 10px 10px 10px 0;
    border-color: transparent white transparent transparent;
  }

  /* Make sure all circles are at the same spot */
  .left::after, .right::after {
    left: 15px;
  }

  /* Make all right containers behave like the left ones */
  .right {
    left: 0%;
  }
}
</style>

</head>

<body>




<div class="timeline">
  <div class="text-justify">
  <div class="container left">
    <div class="content">
      <h2>Evolução</h2>
      <p>Descreva uma breve historia do Paciente</p>
      <h5>Data Atual <p id="datas"></p> </h5>
      
      <html><table><textarea rows="10" cols="40" id='result'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>

    </div>
  </div>

  <div class="timeline2">
    <div class="text-justify">
  <div class="container right">
    <div class="content">
      <h2>Evolução</h2>
    <p>Descreva uma breve historia do Paciente</p>
      <html><table><textarea rows="10" cols="40" id='timeline2'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>
    </div>
  </div>
    <div class="timeline3">
  <div class="container left">
    <div class="content">
      <h2>Evolução</h2>
      <p>Descreva uma breve historia do Paciente</p>
      <html><table><textarea rows="10" cols="40" id="timeline3">'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>
    </div>
  </div>
  <div class="container right">
    <div class="content">
      <h2>Evolução</h2>
      <p>Descreva uma breve historia do Paciente</p>
      <html><table><textarea rows="10" cols="40" id='result'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>
    </div>
  </div>
  <div class="container left">
    <div class="content">
      <h2>Evolução</h2>
      <p>Descreva uma breve historia do Paciente</p>
      <html><table><textarea rows="10" cols="40" id='result'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>
    </div>
  </div>
  <div class="container right">
    <div class="content">
      <h2>Evolução</h2>
      <p>Descreva uma breve historia do Paciente</p>
      <html><table><textarea rows="10" cols="40" id='result'>Escreva aqui seu lembrete</textarea></table></html>
    <button onClick="salvar()">Salvar</button>
    </div>
  </div>
</div>
<script>

    function salvar() {
        // Check browser support
        if (typeof(Storage) !== "undefined") {
            // Store
            localStorage.setItem("text", document.getElementById("result").value);

        } else {
            document.getElementById("result").innerHTML = "Local Storage não suportado";
        }
    }

    // Retrieve
        document.getElementById("result").innerHTML = localStorage.getItem("text");
    </script>

<script>
var d = new Date();
document.getElementById("datas").innerHTML = d;
</script>

    </body>
</html>

usuarios/templates/usuarios - Copia/perfil - Cópia.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
  <title>Cadastro Médico</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style>    
    /* Set black background color, white text and some padding */
    footer {
      background-color: #555;
      color: white;
      padding: 15px;
    }
  </style>
</head>
<body>

<nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">Relacionamento Médico</a>
        </div>
    <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'home' %}">Sobre</a></li>
            {% comment %}
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
            {% endcomment %}

            {% if request.user.is_authenticated %}
            <li class="dropdown">
              <a href="{% url 'usuarios:perfil_usuario' %}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Perfil <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href={% url 'usuarios:perfil_usuario' %}>Ver</a></li>
                <li><a {% if active_link == "usuarios:editar_perfil" %}class="active"{% endif %} href="{% url 'usuarios:editar_perfil' %}">Editar</a></li>
                {% comment %}
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
                {% endcomment %}
              </ul>
            </li>
            <li class=""><a href="{% url 'prestadores:cadastro_prestador_pf' %}">Enviar Cadastro</a></li>
            <li {% if active_link == "cadastros_list" %}class="active"{% endif %}><a href="{% url 'prestadores:cadastros_list' %}">Cadastros Enviados</a></li>

            {% endif %}

          </ul>


        {% block nav_user %}
          <ul class="nav navbar-nav navbar-right">
          {% if request.user.is_authenticated %}
              <li id="nav-username"><a href="{% url 'usuarios:perfil_usuario' %}">
                <span class="glyphicon glyphicon-user"></span>  {{ user.get_username }} &nbsp; </a>
              </li>
              <li>
                <a href="{% url 'auth_logout' %}">Logout</a>
              </li>
          {% else %}
            <li><a href="{% url 'registration_register' %}">Registrar</a></li>
          {% endif %}
          </ul>
            {% if not request.user.is_authenticated and not "/accounts/login" in request.get_full_path %}
            <form class="navbar-form navbar-right"
                  method="POST"
                  action="{% url 'auth_login' %}">
              {% csrf_token %}
                <div class="form-group">
                    <input type="text" class="form-control" name="username"  required placeholder="email">
                </div>
                <div class="form-group">
                    <input type="password" class="form-control" name="password" placeholder="senha">
                </div>
              <input type="hidden" name="next" value="{% url 'home' %}" />
              <button type="submit" class="btn btn-default">Login</button>
            </form>
          {% endif %}
        {% endblock %}
         </div><!--/.navbar-collapse -->
      </div>
    </nav>

  
<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
        <p><a href="#">Meu Perfil</a></p>
        <img src="/media/HOSPITAL_CASA" class="img-circle" height="65" width="65" alt="HOSPITAL_CASA">
      </div>
      <div class="well">
        <p><a href="#">Interests</a></p>
        <p>
          <span class="label label-default">Noticias</span>
          <span class="label label-primary">Esportes</span>
          <span class="label label-success">Viagens</span>
          <span class="label label-info">Futebol</span>
          <span class="label label-warning">Jogos</span>
          <span class="label label-danger">Saúde</span>
        </p>
      </div>
      <div class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
        <p><strong>Este é o seu Perfil</strong></p>
        Seu espaço para criar seu perfil profissional no Grupo Hospital Casa.
      </div>
      <a href="http://twitter.com/share" class="twitter-share-button"
data-url="www.grupohospitalcasa.com.br/" data-text="HospitalCasa" data-count="horizontal" data-via="hospitalcasa" data-lang="pt">Tweetar</a>
<script type="text/javascript" src="http://platform.twitter.com/widgets.js">
</script>

      <iframe src="http://www.facebook.com/plugins/like.php?href=https://www.facebook.com/hospitalcasadeportugal&layout=button_count&
show_faces=true&width=380&action=like&colorscheme=light&height=30&locale=pt_BR" scrolling="no" frameborder="0"
style="border:none; overflow:hidden; width:100px; height:25px;" allowTransparency="true">
<script src="http://connect.facebook.net/pt_BR/all.js#xfbml=1"></script>
<script src="http://static.ak.fbcdn.net/connect.php/js/FB.Share"
type="text/javascript"></script>


</iframe>

    </div>
    <div class="col-sm-7">
    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
              <p contenteditable="true">Status: Feeling Blue</p>
              <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> Like
              </button>     
            </div>
          </div>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>John</p>
           <img src="bird.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Bo</p>
           <img src="bandmember.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Jane</p>
           <img src="bandmember.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-3">
          <div class="well">
           <p>Anja</p>
           <img src="bird.jpg" class="img-circle" height="55" width="55" alt="Avatar">
          </div>
        </div>
        <div class="col-sm-9">
          <div class="well">
            <p>Just Forgot that I had to mention something about someone to someone about how I forgot something, but now I forgot it. Ahh, forget it! Or wait. I remember.... no I don't.</p>
          </div>
        </div>
      </div>     
    </div>
    <div class="col-sm-2 well">
      <div class="thumbnail">
        <p>Upcoming Events:</p>
        <img src="paris.jpg" alt="Paris" width="400" height="300">
        <p><strong>Paris</strong></p>
        <p>Fri. 27 November 2015</p>
        <button class="btn btn-primary">Info</button>
      </div>      
      <div class="well">
        <p>ADS</p>
      </div>
      <div class="well">
        <p>ADS</p>
      </div>
    </div>
  </div>
</div>

<footer class="container-fluid text-center">
  <p>Footer Text</p>
</footer>

</body>
</html>