core/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path,include, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.views import static as ds

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from core.views import LoginView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('registration.backends.simple.urls')),
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    #path('usuarios/create_user', CreateUserView.as_view(), name='create_user'),
    path('usuarios/',include('usuarios.urls')),
    path('', views.home1, name='home1'),
    path('todolist/',include('todolist.urls')),
    path('agendaFinanceira/',include('agendaFinanceira.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),  # URL para obter um token de autenticação


    re_path(r'^prestador/', include(('usuarios.urls', 'usuarios'),namespace='usuarios')),
    re_path(r'^prestador/', include(('prestadores.urls','prestadores'),namespace='prestadores')),
    re_path(r'^select2/', include('django_select2.urls')),
     

    re_path(r'^media/(?P<path>.*)$', ds.serve,
            {'document_root': settings.MEDIA_ROOT, }, name="media"),
] 
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prestadores/urls.py
from django.urls import path
#from django.conf.urls import url,re_path
from django.urls import path, re_path, include
from . import views

urlpatterns = [
    path('cadastro-prestador-pf', views.cadastro_prestador_pf, name='cadastro_prestador_pf'),
    path('cadastro/dados-pessoais', views.dados_pessoais, name='dados_pessoais'),
    path('cadastro/cadastros_list',views.cadastros_list, name='cadastros_list'),
    path('cadastro/sucesso', views.sucesso2, name='sucesso'),
    re_path('cadastro/(?P<pk>[0-9]+)/$',views.cadastro_enviado,name='cadastro_prestadorpf')
]

prestadores/models.py
from django.db import models
from usuarios.models import User
from core.helpers import validate_CPF, validate_file_extension
 



def identidade_frente_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.nr_cpf_cgc, "id_frente_"+filename)




class Especialidade(models.Model):
    nm_especialidade = models.CharField(blank=False, max_length=100)
    def __str__(self):
        return self.nm_especialidade
     
       

STATUS_CADASTRO = (
    ('PENDENTE', 'Aguardando Validação'),
    ('VALIDADO', 'Validado (Ativo)'),
    ('INVALIDO', 'Inválido'),
    ('INATIVO', 'Inativo'),
)
class PrestadorPessoaFisica(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Enviado em")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Atualizado em")
    status=models.CharField(max_length=30, choices=STATUS_CADASTRO, default='PENDENTE')
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    cd_prestador = models.IntegerField(unique=False,blank=True, null=True)
    nm_prestador = models.CharField(verbose_name="Nome Completo", max_length=100)
    nr_cpf_cgc = models.CharField(verbose_name="CPF",max_length=11,validators=[validate_CPF])
    dt_nascimento = models.DateField(verbose_name="Data de Nascimento", blank=True, null=True)
    ds_email = models.EmailField(verbose_name="Email", max_length=200, blank=True, null=True)
    nr_cep = models.CharField(verbose_name="CEP", max_length=8,blank=True, null=True)
    ds_endereco = models.CharField(verbose_name="Endereço", max_length=200, blank=True, null=True)
    ds_complemento = models.CharField(verbose_name="Complemento", max_length=20, blank=True, null=True)
    ds_bairro = models.CharField(verbose_name="Bairro", max_length=200, blank=True, null=True)
    nm_cidade = models.CharField(verbose_name="Cidade", max_length=200, blank=True, null=True)
    cd_uf = models.CharField(verbose_name="UF", max_length=200, blank=True, null=True)
    nr_fone_contato = models.CharField(verbose_name="Telefone para Contato", max_length=20,blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True,verbose_name="Observações")
    data_insercao = models.DateTimeField(auto_now_add=True)
    identidade_frente =models.FileField(verbose_name="Documento", upload_to=identidade_frente_directory_path,validators=[validate_file_extension], blank=True, null=True)
    especialidades = models.OneToOneField(Especialidade, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.nm_prestador)

prestadores/forms.py
from django.forms import ModelForm
from django import forms

from .models import PrestadorPessoaFisica, Especialidade

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit, HTML, Button, Row, Field, Fieldset
from crispy_forms.layout import Submit, Layout, Div, Fieldset
from crispy_forms.bootstrap import Field, InlineRadios, TabHolder, Tab
from crispy_forms.helper import FormHelper

from crispy_forms.layout import Submit, Layout, Div, Fieldset

from crispy_forms.bootstrap import AppendedText, PrependedText, FormActions
from django.urls import reverse


from django_select2.forms import (
    HeavySelect2MultipleWidget, HeavySelect2Widget, ModelSelect2MultipleWidget,
    ModelSelect2TagWidget, ModelSelect2Widget, Select2MultipleWidget, Select2Widget
)

class PrestadorPessoaFisicaForm(ModelForm):
    # Uni-form
    # helper = FormHelper()
    # helper.form_class = 'form-horizontal'
    # helper.layout = Layout(
    #     FormActions(
    #         Submit('save_changes', 'Save changes', css_class="btn-primary"),
    #         Submit('cancel', 'Cancel'),
    #     )
    # )
    def __init__(self, *args, **kwargs):
        super(PrestadorPessoaFisicaForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-prestador-data-form'
        self.helper.form_method = 'post'
        # self.helper.form_action = reverse('index')
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div(Field('nm_prestador'), css_class="col-md-8", ),
                css_class="row",
            ),
            Div(
                Div(Field('dt_nascimento'), css_class="col-md-3", ),
                Div(Field('nr_cpf_cgc'), css_class="col-md-4", ),
                css_class="row", ),
            Div(
                Div(Field('especialidades'), css_class="col-md-8", ),
                css_class="row", ),
            #Div(
            #    Div(Field('nm_pai'), css_class="col-md-6", ),
            #    Div(Field('ds_faculdade'), css_class="col-md-3", ),
                
            #    css_class="row", ),
            Div(
                Div(Field('ds_email'), css_class="col-md-4", ),
                css_class="row", ),
            Div(
                Div(Field('nr_cep'), css_class="col-md-2", ),
                Div(Field('ds_endereco'), css_class="col-md-8", ),
                Div(Field('ds_complemento'), css_class="col-md-2", ),
                css_class="row", ),
            Div(
                Div(Field('ds_bairro'), css_class="col-md-3", ),
                Div(Field('nm_cidade'), css_class="col-md-4", ),
                Div(Field('cd_uf'), css_class="col-md-2", ),
                Div(Field('nr_fone_contato'), css_class="col-md-3", ),
                css_class="row", ),
            Div(
                Div(Field('identidade_frente',css_class="filestyle",data_input="false",data_buttonText="Upload"), css_class="col-md-3", ),
                #Div(Field('identidade_verso',css_class="filestyle",data_input="false",data_buttonText="Upload"), css_class="col-md-3", ),
                #Div(Field('comprovante_residencia',css_class="filestyle",data_input="false",data_buttonText="Upload"), css_class="col-md-3", ),
            css_class="row", ),

            Div(
                Div(Field('observacoes'), css_class="col-md-12 col-centered", ),
                css_class="row", ),
            Submit('submit', 'Enviar', css_class='btn-success col-centered')
        )

    class Meta:
        model = PrestadorPessoaFisica
        # fields = ['sn_cirurgiao', 'nm_prestador', 'nr_cpf_cgc', 'dt_nascimento', 'nm_mae', 'nm_pai',
        #           'ds_codigo_conselho', 'especialidades',
        #           'ds_faculdade', 'ds_email', 'nr_cep', 'ds_endereco', 'ds_complemento', 'ds_bairro', 'nm_cidade',
        #           'cd_uf', 'banco','ds_agencia', 'nr_conta', 'nr_fone_contato', 'identidade_frente', 'identidade_verso',
        #           'comprovante_residencia',
        #           'observacoes']
        fields = ['nm_prestador', 'nr_cpf_cgc', 'dt_nascimento', #'nm_mae', 'nm_pai','ds_codigo_conselho', 
                  'especialidades',
                  #'ds_faculdade', 
                  'ds_email', 'nr_cep', 'ds_endereco', 'ds_complemento', 'ds_bairro', 'nm_cidade',
                  'cd_uf', 
                  #'banco','ds_agencia', 'nr_conta', 
                  'nr_fone_contato', 
                  'identidade_frente', 
                  #'identidade_verso',
                  #'comprovante_residencia',
                  'observacoes']
        widgets = {
            'especialidades': Select2MultipleWidget
        }

        # self.helper.add_input(Submit('submit', 'Enviar', css_class='btn-success'))

        # self.helper.layout = Layout(
        #     Div('sn_cirurgiao',css_class="col-lg-4",),
        #     Div('nm_prestador'),
        #     Div('nr_cpf_cgc'),
        #     Div('dt_nascimento'),
        #     #
        #     # Fieldset('Dados Pessoais',
        #     #          Field('nm_tip_presta', placeholder='Tipo de Prestador',
        #     #                css_class="some-class"),
        #     #          Div('sn_cirurgiao', title="Cirurgião?"), ),
        #     # Fieldset('Contact data', 'nm_prestador', 'nr_cpf_cgc', style="color: brown;"),
        #     # InlineRadios('color'),
        #     # TabHolder(Tab('Address', 'address'),
        #     #           Tab('More Info', 'more_info'))
        # )



        # # You can dynamically adjust your layout
        # self.helper.layout.append(Submit('save', 'Enviar'))


#
# class NewPrestadorForm(forms.Form):
#     name = forms.CharField(
#         max_length=255,
#         widget=forms.Textarea(
#             attrs={'class': 'custom'},
#         ),
#     )


class DadosPessoaisForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(DadosPessoaisForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-dados-pessoais-form'
        self.helper.form_method = 'post'
        # self.helper.form_action = reverse('index')
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div(Field('nm_prestador'), css_class="col-md-6", ),
                Div(Field('nr_cpf_cgc'), css_class="col-md-4", ),
                Div(Field('dt_nascimento'), css_class="col-md-2", ),
                css_class="row", ),
            #Div(
            #    Div(Field('nm_mae'), css_class="col-md-6", ),
            #    Div(Field('nm_pai'), css_class="col-md-6", ),
             #   css_class="row", ),
            Div(
                Div(Field('nr_cep'), css_class="col-md-2", ),
                Div(Field('ds_endereco'), css_class="col-md-8", ),
                Div(Field('ds_complemento'), css_class="col-md-2", ),
                css_class="row", ),
            Div(
                Div(Field('ds_bairro'), css_class="col-md-3", ),
                Div(Field('nm_cidade'), css_class="col-md-4", ),
                Div(Field('cd_uf'), css_class="col-md-2", ),
                css_class="row", ),
            Submit('submit', 'Enviar', css_class='btn-success col-centered')
        )
    class Meta:
        model = PrestadorPessoaFisica
        fields = ['nm_prestador','nr_cpf_cgc','dt_nascimento',#'nm_mae','nm_pai',
                  'nr_cep','ds_endereco','ds_complemento','ds_bairro','nm_cidade','cd_uf','observacoes']
        exclude=['usuario']
        widgets= {
            'especialidades': Select2MultipleWidget,
        }

prestadores/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required, permission_required

from usuarios.models import User
# Create your views here.
from .models import PrestadorPessoaFisica, Especialidade

from .forms import PrestadorPessoaFisicaForm, DadosPessoaisForm
from django.shortcuts import get_object_or_404
from django.core import serializers


def sucesso2(request):
    return render(request, 'sucesso.html')

@permission_required
def cadastro_prestador_pf(request):
    if request.method == "POST":
        form = PrestadorPessoaFisicaForm(request.POST, request.FILES,request.user)
        if form.is_valid():
            prestador = form.save(commit=False)
            prestador.user = request.user
            prestador.save()
            return redirect('cadastro/sucesso')
    else:
        form = PrestadorPessoaFisicaForm()
    return render(request, 'cadastro_pessoa_fisica.html', {
        'form': form
    })

@permission_required 
def dados_pessoais(request):
    if request.method == "POST":
        form = DadosPessoaisForm(request.POST, request.FILES)
        if form.is_valid():
            prestador = form.save(commit=False)
            prestador.usuario = request.user
            prestador.save()
            # prestador.save()
            return redirect('sucesso')
    else:
        form = DadosPessoaisForm()
    return render(request, 'dados_pessoais.html', {
        'form': form
    })

  


@permission_required
def cadastros_list(request):
    usuario = request.user
    cadastros = PrestadorPessoaFisica.objects.filter(user=usuario.id).order_by('-created_at')
    return render(request,'cadastros_list.html',{
        'cadastros':cadastros
    })

@permission_required
def cadastro_enviado(request,pk):
    cadastro=get_object_or_404(PrestadorPessoaFisica,pk=pk)
    data = serializers.serialize("python", PrestadorPessoaFisica.objects.filter(pk=pk))
    return render(request,'cadastro_detail.html',{'cadastro':cadastro,'data':data})

prestadores/templates/cadastro_pessoa_fisica.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}



<h1>Cadastro</h1>
<div class='row'>
<div class='col-sm-10 col-sm-offset-1'>
<form method="post" enctype="multipart/form-data">
        {% crispy form %}
</form>
</div>
</div>
<script>
//Verifica se CPF é válido
function TestaCPF(strCPF) {
    var Soma;
    var Resto;
    Soma = 0;
    //strCPF  = RetiraCaracteresInvalidos(strCPF,11);
    if (strCPF.length != 11 || strCPF == "00000000000" || strCPF == "11111111111" ||
     strCPF == "22222222222" || strCPF == "33333333333" || strCPF == "44444444444" ||
     strCPF == "55555555555" || strCPF == "66666666666" || strCPF == "77777777777" ||
     strCPF == "88888888888" || strCPF == "99999999999")
    return false;
    for (i=1; i<=9; i++)
	Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
    Resto = (Soma * 10) % 11;
    if ((Resto == 10) || (Resto == 11))
	Resto = 0;
    if (Resto != parseInt(strCPF.substring(9, 10)) )
	return false;
	Soma = 0;
    for (i = 1; i <= 10; i++)
       Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
    Resto = (Soma * 10) % 11;
    if ((Resto == 10) || (Resto == 11))
	Resto = 0;
    if (Resto != parseInt(strCPF.substring(10, 11) ) )
        return false;
    return true;
}
</script>

<script>
    // Aciona a validação e formatação ao sair do input
    $('#id_nr_cpf_cgc').blur(function(){

        // O CPF ou CNPJ
        var cpf_cnpj = $(this).val();

        // Testa a validação e formata se estiver OK
        if ( TestaCPF( cpf_cnpj ) ) {
        document.getElementById('id_nr_cpf_cgc').style.borderColor = "green";
            <!--alert('OK');-->
        } else {
            <!--alert('CPF ou CNPJ inválido!');-->
            document.getElementById('id_nr_cpf_cgc').style.borderColor = "red";
        }
    });
</script>
    <!-- Adicionando Javascript -->
   <!-- Adicionando Javascript -->
    <script type="text/javascript" >

        $(document).ready(function() {

            function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#id_ds_endereco").val("");
                $("#id_ds_bairro").val("");
                $("#id_nm_cidade").val("");
                $("#id_cd_uf").val("");
                $("#ibge").val("");
            }

            //Quando o campo cep perde o foco.
            $("#id_nr_cep").blur(function() {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if(validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#id_ds_endereco").val("...");
                        $("#id_ds_bairro").val("...");
                        $("#id_nm_cidade").val("...");
                        $("#id_cd_uf").val("...");
                        $("#ibge").val("...");

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#id_ds_endereco").val(dados.logradouro);
                                $("#id_ds_bairro").val(dados.bairro);
                                $("#id_nm_cidade").val(dados.localidade);
                                $("#id_cd_uf").val(dados.uf);
                                $("#ibge").val(dados.ibge);
                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });
        });

    </script>
{% endblock %}

prestadores/templates/cadastros_list.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}



<h1>Cadastros Enviados</h1>
<div class='row'>
<div class='col-sm-10 col-sm-offset-1'>
<table class="table table-hover table-auto">
    <thead>
    <tr>
        <th>Status</th>
        <th>Data de Envio</th>
        <th>Horário de Envio</th>
        <th>Email</th>
        <th>CRM</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    {% for cadastro in cadastros %}
        <tr>
            <td>{{cadastro.status}}</td>
            <td>{{cadastro.created_at|date:"d/m/Y"}}</td>
            <td>{{cadastro.created_at|time:"h:i:s"}}</td>
            <td>{{cadastro.ds_email}}</td>
            <td>{{cadastro.ds_codigo_conselho}}</td>
            <td><a href="{% url 'prestadores:cadastro_prestadorpf' pk=cadastro.pk %}">Ver cadastro</a></td>
        </tr>
    {% endfor %}
</table>
</div>
</div>
{% endblock %}

prestadores/templates/dados_pessoais.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}



<h1>Dados Pessoais</h1>
<div class='row'>
<div class='col-sm-10 col-sm-offset-1'>
<form method="post" enctype="multipart/form-data">
        {% crispy form %}
</form>
</div>
</div>
<script>
//Verifica se CPF é válido
function TestaCPF(strCPF) {
    var Soma;
    var Resto;
    Soma = 0;
    //strCPF  = RetiraCaracteresInvalidos(strCPF,11);
    if (strCPF.length != 11 || strCPF == "00000000000" || strCPF == "11111111111" ||
     strCPF == "22222222222" || strCPF == "33333333333" || strCPF == "44444444444" ||
     strCPF == "55555555555" || strCPF == "66666666666" || strCPF == "77777777777" ||
     strCPF == "88888888888" || strCPF == "99999999999")
    return false;
    for (i=1; i<=9; i++)
	Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (11 - i);
    Resto = (Soma * 10) % 11;
    if ((Resto == 10) || (Resto == 11))
	Resto = 0;
    if (Resto != parseInt(strCPF.substring(9, 10)) )
	return false;
	Soma = 0;
    for (i = 1; i <= 10; i++)
       Soma = Soma + parseInt(strCPF.substring(i-1, i)) * (12 - i);
    Resto = (Soma * 10) % 11;
    if ((Resto == 10) || (Resto == 11))
	Resto = 0;
    if (Resto != parseInt(strCPF.substring(10, 11) ) )
        return false;
    return true;
}
</script>

<script>
    // Aciona a validação e formatação ao sair do input
    $('#id_nr_cpf_cgc').blur(function(){

        // O CPF ou CNPJ
        var cpf_cnpj = $(this).val();

        // Testa a validação e formata se estiver OK
        if ( TestaCPF( cpf_cnpj ) ) {
        document.getElementById('id_nr_cpf_cgc').style.borderColor = "green";
            <!--alert('OK');-->
        } else {
            <!--alert('CPF ou CNPJ inválido!');-->
            document.getElementById('id_nr_cpf_cgc').style.borderColor = "red";
        }
    });
</script>
    <!-- Adicionando Javascript -->
   <!-- Adicionando Javascript -->
    <script type="text/javascript" >

        $(document).ready(function() {

            function limpa_formulário_cep() {
                // Limpa valores do formulário de cep.
                $("#id_ds_endereco").val("");
                $("#id_ds_bairro").val("");
                $("#id_nm_cidade").val("");
                $("#id_cd_uf").val("");
                $("#ibge").val("");
            }

            //Quando o campo cep perde o foco.
            $("#id_nr_cep").blur(function() {

                //Nova variável "cep" somente com dígitos.
                var cep = $(this).val().replace(/\D/g, '');

                //Verifica se campo cep possui valor informado.
                if (cep != "") {

                    //Expressão regular para validar o CEP.
                    var validacep = /^[0-9]{8}$/;

                    //Valida o formato do CEP.
                    if(validacep.test(cep)) {

                        //Preenche os campos com "..." enquanto consulta webservice.
                        $("#id_ds_endereco").val("...");
                        $("#id_ds_bairro").val("...");
                        $("#id_nm_cidade").val("...");
                        $("#id_cd_uf").val("...");
                        $("#ibge").val("...");

                        //Consulta o webservice viacep.com.br/
                        $.getJSON("https://viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {

                            if (!("erro" in dados)) {
                                //Atualiza os campos com os valores da consulta.
                                $("#id_ds_endereco").val(dados.logradouro);
                                $("#id_ds_bairro").val(dados.bairro);
                                $("#id_nm_cidade").val(dados.localidade);
                                $("#id_cd_uf").val(dados.uf);
                                $("#ibge").val(dados.ibge);
                            } //end if.
                            else {
                                //CEP pesquisado não foi encontrado.
                                limpa_formulário_cep();
                                alert("CEP não encontrado.");
                            }
                        });
                    } //end if.
                    else {
                        //cep é inválido.
                        limpa_formulário_cep();
                        alert("Formato de CEP inválido.");
                    }
                } //end if.
                else {
                    //cep sem valor, limpa formulário.
                    limpa_formulário_cep();
                }
            });
        });

    </script>
{% endblock %}

prestadores/templates/register-paciente.html
{% extends "base.html" %}
{% block content %}

     <h1 class="text-center">Cadastrar Pacientes</h1>
     
     <form enctype="multipart/form-data" action="submit", method="POST">{% csrf_token %}
     <div class="container">
     	<div class="form-group">
     		<label>E-mail</label>
     	    <input class="form-control" name="Email" type="text">
      </div>
        <div class="form-group">
     		<label>Telefone:</label>
     	    <input class="form-control" name="Telefone" type="number">
      </div>
        <div class="form-group">
     		<label>Nome Completo:</label>
     	    <input class="form-control" name="Paciente" type="text">
      </div>
        <div class="form-group">
     		<label for="description">Descrição</label>
     	    <textarea class="form-control" rows="5" name="description"></textarea>
      </div>
        <div class="form-group">
        	<input type="file" class="form-control-file border" name="file" accept="image/*"></input>
        </div>
        <button type="submit" class="btn btn-primary">
        	Cadastrar
        </button>
        
        </form>

     </div>

{% endblock %}     