core/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path,include, re_path
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.views import static as ds

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
from core.views import LoginView
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/', include('registration.backends.simple.urls')),
    #path('login/', auth_views.LoginView.as_view(), name='login'),
    path('', views.home, name='home'),
    path('login/', LoginView.as_view(), name='login'),
    #path('usuarios/create_user', CreateUserView.as_view(), name='create_user'),
    path('usuarios/',include('usuarios.urls')),
    path('', views.home1, name='home1'),
    path('todolist/',include('todolist.urls')),
    path('agendaFinanceira/',include('agendaFinanceira.urls')),
    path('api-token-auth/', obtain_auth_token, name='api_token_auth'),  # URL para obter um token de autenticação


    re_path(r'^prestador/', include(('usuarios.urls', 'usuarios'),namespace='usuarios')),
    re_path(r'^prestador/', include(('prestadores.urls','prestadores'),namespace='prestadores')),
    re_path(r'^select2/', include('django_select2.urls')),
     

    re_path(r'^media/(?P<path>.*)$', ds.serve,
            {'document_root': settings.MEDIA_ROOT, }, name="media"),
] 
urlpatterns  +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todolist/models.py
from django.db import models
from usuarios.models import User
from django.conf import settings
from django.utils import timezone

class todolist(models.Model):
    title = models.CharField(max_length=40, verbose_name="Titulo")
    description = models.TextField(blank=True, verbose_name="Descrição")
    created = models.DateTimeField(auto_now=True)
    datecompleted = models.DateTimeField(null=True, blank=True, verbose_name="Conclusão da Atividade")
    priority = models.BooleanField(default=False, verbose_name="Prioridade")
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, related_name="user_todolist")
    date_conclusao = models.DateTimeField(default=timezone.now, verbose_name="Data da Atividade")
    is_completed = models.BooleanField(default=False, verbose_name="Atividade Realizada")
    postpone_date = models.DateTimeField(null=True, blank=True, verbose_name="Postergar Data")
    email = models.EmailField(blank=True, null=True, verbose_name="Email para Redirecionamento")
    redirected_user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="redirected_todolist")

    def __str__(self):
        return self.title

usuarios/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
#from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _
from django.db.models.signals import post_save

from core.helpers import validate_CPF

def foto_perfil_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '{0}/{1}'.format(instance.user.email, "perfil_"+filename)

class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('endereço de email'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

STATUS_SEXO = (
    ('1:', 'MASCULINO'),
    ('2:', 'FEMININO'),
    ('3:', 'OUTROS VALORES'),
    
)
STATUS_TIPO = (
    ('1:', 'ADMINISTRADOR'),
    ('2:', 'CLIENTE'),
    ('3:', 'OUTROS'),
    
)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    nm_completo = models.CharField(verbose_name="Nome Completo", max_length=100,null=True, blank=True)
    nr_cpf_cgc = models.CharField(verbose_name="CPF",max_length=11,null=True, blank=True,validators=[validate_CPF])
    foto_perfil = models.ImageField(upload_to=foto_perfil_directory_path, null=True, blank=True)
    cidade = models.CharField(verbose_name="Cidade", max_length=200, blank=True, null=True)
    observacoes = models.TextField(blank=True, null=True,verbose_name="Observações")
    idade = models.IntegerField(null=True)
    sexo = models.CharField(max_length=20, choices=STATUS_SEXO, default='OUTROS VALORES')
    tipo_usuario = models.CharField(max_length=30, choices=STATUS_TIPO, default='CLIENTE')
    nrTelCelular = models.CharField(max_length=11, blank=True, null=True, verbose_name='Nº telefone celular')

    def __str__(self):
       return str(self.nm_completo)

    class Meta:
        verbose_name = "perfil"
        verbose_name_plural = "perfis"

def create_profile(sender, **kwargs):
    user = kwargs["instance"]
    if kwargs["created"]:
        user_profile = UserProfile(user=user)
        user_profile.save()
post_save.connect(create_profile, sender=User)

agendaFinanceira/forms.py
from django.forms import ModelForm
from django.urls import reverse
from django import forms
from django.forms import ModelForm
from .models import Cliente, Receita, Despesa, LancamentoContasPagar, Fornecedor, SaldoAtual, SaldoInicial, Produto
from dal import autocomplete
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Submit
from crispy_forms.bootstrap import Field
from crispy_forms.helper import FormHelper
from dal import autocomplete
from django_select2.forms import ModelSelect2Widget,Select2MultipleWidget
from django.forms.widgets import DateInput





class FornecedorForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FornecedorForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-fornecedor-form'
        self.helper.form_method = 'post'
        # self.helper.form_action = reverse('index')
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div(Field('nm_fornecedor'), css_class="col-md-6"),
                Div(Field('telefone'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('endereco'), css_class="col-md-6"),
                Div(Field('cidade'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('uf'), css_class="col-md-2"),
                Div(Field('tipo'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('email'), css_class="col-md-4"),
                css_class="row"),
            Div(
                Div(Field('cnpj_cpf'), css_class="col-md-3"),
                css_class="row"),
            Submit('submit', 'Enviar', css_class='btn-success col-centered')
        )
    class Meta:
        model = Fornecedor
        fields = ['nm_fornecedor','endereco','cidade','uf','telefone','email','tipo','cnpj_cpf']
        exclude=['cd_forncedor', 'usuario']
            
                

class ClienteForm(forms.ModelForm):
    
    class Meta:
        model = Cliente
        fields = ['nm_cliente', 'endereco', 'cidade', 'uf', 'telefone', 'email', 'tipo', 'cnpj_cpf']
        widgets = {
            'endereco': forms.TextInput(attrs={'placeholder': 'Endereço'}),
            'cidade': forms.TextInput(attrs={'placeholder': 'Cidade'}),
            'uf': forms.TextInput(attrs={'placeholder': 'UF'}),
            'email': forms.EmailInput(attrs={'placeholder': 'E-mail'}),
            'cnpj_cpf': forms.TextInput(attrs={'placeholder': 'CNPJ/CPF'}),
        }

    def __init__(self, *args, **kwargs):
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['nm_cliente'].required = True
        self.fields['telefone'].required = True
        self.fields['endereco'].required = False 
        self.fields['cidade'].required = False
        self.fields['uf'].required = False
        self.fields['email'].required = False
        self.fields['tipo'].required = False
        self.fields['cnpj_cpf'].required = False

class DespesaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(DespesaForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-despesa-form'
        self.helper.form_method = 'post'
        # self.helper.form_action = reverse('index')
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div(Field('nome_credor'), css_class="col-md-6"),
                Div(Field('valor'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('data_vencimento'), css_class="col-md-6"),
                Div(Field('situacao'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('tipo_despesa'), css_class="col-md-2"),
                Div(Field('modo_pag'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('image'), css_class="col-md-4"),
                css_class="row"),
            Div(
                Div(Field('observacoes'), css_class="col-md-3"),
                css_class="row"),
            Submit('submit', 'Enviar', css_class='btn-success col-centered')
        )
    class Meta:
        model = Despesa
        fields = ['nome_credor','valor','data_vencimento','situacao','observacoes','tipo_despesa','modo_pag','image']
        exclude=['id_despesa', 'usuario','created_at']
        


class ProdutoForm(forms.ModelForm):
    class Meta:
        model = Produto
        fields = ['nm_produto', 'status_produto', 'valor_venda', 'valor_producao', 'image'] 
        widgets = {
            'dt_criacao': DateInput(attrs={'type': 'date'})
        }
        exclude = ['usuario']        
        


class ReceitaForm(forms.ModelForm):
    produto = forms.ModelChoiceField(queryset=Produto.objects.all(), required=False)  

    class Meta:
        model = Receita
        fields = ['valor', 'cliente', 'data_entrada', 'forma_recebimento', 'situacao', 'observacoes', 'quantidade', 'produto']  
        widgets = {
            'cliente': autocomplete.ModelSelect2(url='cliente-autocomplete'),
            'produto': autocomplete.ModelSelect2(url='produto-autocomplete'),
            'data_entrada': DateInput(attrs={'type': 'date'})
        }
        exclude = ['usuario', 'created_at']


class LancamentoContasPagarForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(LancamentoContasPagarForm, self).__init__(*args, **kwargs)
        # If you pass FormHelper constructor a form instance
        # It builds a default layout with all its fields
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-contasapagar-form'
        self.helper.form_method = 'post'
        # self.helper.form_action = reverse('index')
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div(Field('data_docto'), css_class="col-md-3"),
                Div(Field('despesa'), css_class="col-md-4"),
                css_class="row"),
            Div(
                Div(Field('documento'), css_class="col-md-3"),
                Div(Field('plano_conta'), css_class="col-md-3"),
                Div(Field('conta'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('pago_pelo_banco'), css_class="col-md-4"),
                Div(Field('valor'), css_class="col-md-2"),
                Div(Field('parcelas'), css_class="col-md-2"),
                css_class="row"),
            Div(
                Div(Field('valor_parcela'), css_class="col-md-3"),
                Div(Field('vencimento'), css_class="col-md-3"),
                css_class="row"),
            Div(
                Div(Field('pagamento'), css_class="col-md-4"),
                Div(Field('status'), css_class="col-md-4"),
                css_class="row"),
            Div(
                Div(Field('tipo'), css_class="col-md-4"),
                Div(Field('fornecedor'), css_class="col-md-8"),
                css_class="row"),
            Div(
                Div(Field('descricao'), css_class="col-md-8"),
                css_class="row"),
            Submit('submit', 'Enviar', css_class='btn-success col-centered')
        )

    class Meta:
        model = LancamentoContasPagar
        fields = ['data_docto', 'documento', 'plano_conta', 'conta', 'documento', 'tipo', 'fornecedor',
                  'descricao', 'pago_pelo_banco', 'valor', 'parcelas', 'valor_parcela', 'vencimento', 'pagamento',
                  'status', 'despesa']
        widgets = {
            'fornecedor': Select2MultipleWidget,
        }
      

class SaldoForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SaldoForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-saldo-form'
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div('banco', css_class="col-md-6"),
                css_class="row"),
            Div(
                Div('saldo', css_class="col-md-6"),
                css_class="row"),
            Div(
                Div('data_inicial', css_class="col-md-5"),
                css_class="row"),
            Submit('submit', 'Enviar', css_class='btn btn-success col-centered')
        )

    class Meta:
        model = SaldoInicial
        fields = ['banco','saldo','data_inicial']
        exclude = ['usuario','created_at']
        
class SaldoAtlForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SaldoAtlForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_id = 'id-atual-form'
        self.helper.form_method = 'post'
        self.helper.form_class = 'form-horizontal'
        self.helper.layout = Layout(
            Div(
                Div('banco', css_class="col-md-6"),
                css_class="row"),
            Div(
                Div('saldo_atual', css_class="col-md-6"),
                css_class="row"),
            Div(
                Div('data_atual', css_class="col-md-5"),
                css_class="row"),
            Submit('submit', 'Enviar', css_class='btn btn-success col-centered')
        )

    class Meta:
        model = SaldoAtual
        fields = ['banco','saldo_atual','data_atual']
        exclude = ['usuario', 'created_at']        
        
        

templates/agendaFinanceiraApp/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Agenda Financeira</title>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Select2 CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="https://cdn.datatables.net/2.0.3/css/dataTables.bootstrap5.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>

    <!-- Bootstrap Bundle JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0/js/bootstrap.bundle.min.js"></script>

    <!-- Select2 JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

    <!-- DataTables JS -->
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.js"></script>
    <script src="https://cdn.datatables.net/2.0.3/js/dataTables.bootstrap5.js"></script>

    <script src="https://code.highcharts.com/highcharts.src.js"></script>


    <!-- Custom JS -->
    <script src="{% static 'js/custom.js' %}"></script>
    <style>
        .card {
            position: relative;
            display: -ms-flexbox;
            display: flex;
            -ms-flex-direction: column;
            flex-direction: column;
            width: 90%;
            /* Defina a largura máxima desejada */
            height: 400px;
            /* Defina a altura desejada */
            overflow: hidden;
            /* Para garantir que o conteúdo não extrapole o card */
            word-wrap: break-word;
            background-color: #fff;
            background-clip: border-box;
            border: 2px solid rgba(0, 0, 0, .125);
            border-radius: 0.35rem;
            transition: transform 0.2s;
        }

        .card img {
            max-width: 70%;
            /* Garanta que a imagem não exceda o tamanho do card */
            height: auto;
            /* Ajuste a altura automaticamente para manter a proporção original */
            object-fit: cover;
            /* Ajuste a imagem para cobrir todo o espaço disponível */
        }
        .produto-card {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-between;
        }
        .produto-card .card {
            width: calc(33.33% - 20px); /* Defina a largura desejada para cada card, ajustando conforme necessário */
            margin-bottom: 20px;
        }
        @media (max-width: 768px) {
            .produto-card .card {
                width: calc(50% - 20px); /* Altera a largura dos cards para 50% em dispositivos menores */
            }
        }

        .card:hover {
            transform: translateY(-5px);
            /* Efeito de levantar ligeiramente ao passar o mouse */
        }

        .navbar-light .navbar-brand {
            color: rgba(210, 210, 210);
        }

        @media (max-width: 767px) {
            .card {
                width: 100%;
                margin-bottom: 20px;
            }
        }
    </style>
</head>
<body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{% url 'home' %}">HOME</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Cadastros
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="{% url 'cadastrar_cliente' %}"><i class="bi bi-person-plus"></i> Cadastrar Clientes</a></li>
                      <li><a class="dropdown-item" href="{% url 'cliente_list' %}"><i class="bi bi-person-lines-fill"></i> Visualizar Clientes</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'cadastrar_fornecedor' %}"><i class="bi bi-truck"></i> Cadastrar Fornecedor</a></li>
                      <li><a class="dropdown-item" href="{% url 'fornecedor_list' %}"><i class="bi bi-truck-flatbed"></i> Visualizar Fornecedor</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'cadastrar_despesa' %}"><i class="bi bi-cash-coin"></i> Cadastrar Despesas</a></li>
                      <li><a class="dropdown-item" href="{% url 'despesa_list' %}"><i class="bi bi-cash-stack"></i> Visualizar Despesas</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'cadastrar_receita' %}"><i class="bi bi-cash"></i> Cadastrar Receitas</a></li>
                      <li><a class="dropdown-item" href="{% url 'receitas_list' %}"><i class="bi bi-cash-coin"></i> Visualizar Receita</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{% url 'cadastrar_contasapagar' %}"><i class="bi bi-credit-card"></i> Cadastrar Contas a pagar</a></li>
                    </ul>
                  </li>
                </ul>
                <ul class="navbar-nav">
                  <li class="nav-item">
                    <p class="navbar-text me-2">Conectado como {{ user.get_full_name }} | {{ user.get_username }}</p>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'auth_logout' %}">Sair</a>
                  </li>
                </ul>
              </div>
            </div>
          </nav>
          
    
    <div class="container">
        <main>
            {% block content %}
            {% endblock %}
        </main>
    </div>
    
    <!-- Datepicker -->
    <script>
        $(document).ready(function() {
            $('#data-entrada').datepicker({
                format: 'dd/mm/yyyy',
                language: 'pt-BR',
                autoclose: true,
                todayHighlight: true
            });
        });
    </script>
</body>
</html>

templates/agendaFinanceiraApp/cadastroCliente.html
{% extends 'agendaFinanceiraApp/base3.html' %}

{% block content %}
    <div class="row">
        <p class="card_text">Cadastro de Cliente.</p>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-4 cards_item">
            <div class="card">
                <div class="card_content">
        <form method="post" class="cadastro-form">{% csrf_token %}
            <div class="form-group">   
                <label for="id_nm_cliente" class="form-label">Nome do Cliente:</label>
                {{ form.nm_cliente }}
            </div>
            <div class="form-group">   
                <label for="id_telefone" class="form-label">PIX/Telefone:</label>
                {{ form.telefone }}
            </div>
            <div class="form-group">   
                <label for="id_endereco" class="form-label">Endereço:</label>
                {{ form.endereco }}
            </div>
            <div class="form-group">   
                <label for="id_cidade" class="form-label">Cidade:</label>
                {{ form.cidade }}
            </div>
            <div class="form-group">   
                <label for="id_uf" class="form-label">UF:</label>
                {{ form.uf }}
            </div>
            <div class="form-group">   
                <label for="id_email" class="form-label">PIX/E-mail:</label>
                {{ form.email }}
            </div>
            <div class="form-group">   
                <label for="id_tipo" class="form-label">Tipo:</label>
                {{ form.tipo }}
            </div>
            <div class="form-group">   
                <label for="id_cnpj_cpf" class="form-label">PIX/CPF:</label>
                {{ form.cnpj_cpf }}
            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>
</div>
</div>
</div>
{% endblock content %}

templates/agendaFinanceiraApp/cadastroReceita.html
{% extends 'agendaFinanceiraApp/base.html' %}

{% block content %}
<div class="row">
        <p class="card_text">Cadastro de Receitas.</p>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-lg-4 cards_item">
            <div class="card">
                <div class="card_content">

        <form method="post" class="cadastro-form">{% csrf_token %}
            <div class="row">
                <div class="container">
            <div class="form-group">
                <a href="{% url 'cadastrar_cliente' %}" class="btn btn-primary">Cadastrar Novo Cliente</a>
            </div>
        </div>
        <div class="row">
            <div class="container">
            <div class="form-group">
                <label for="id_cliente" class="form-label"></label>
                {{ form.cliente }}
                <script type="text/javascript">
                    $(document).ready(function() {
                        console.log("Document ready!");
                        console.log("Cliente selecionado:", $("#id_cliente").val()); // Mensagem de depuração
                        $("#id_cliente").select2({
                            placeholder: "Selecione um cliente",
                            ajax: {
                                url: "{% url 'cliente-autocomplete' %}",
                                dataType: 'json',
                                delay: 250,
                                data: function(params) {
                                    return {
                                        q: params.term, // search term
                                        page: params.page
                                    };
                                },
                                processResults: function(data, params) {
                                    console.log("Data received:", data); // Log dos dados recebidos
                                    params.page = params.page || 1;
                                    return {
                                        results: data.results,
                                        pagination: {
                                            more: data.pagination.more
                                        }
                                    };
                                },
                                cache: true
                            },
                            escapeMarkup: function(markup) {
                                return markup;
                            }, // let our custom formatter work
                            minimumInputLength: 1,
                            templateResult: function(repo) {
                                return repo.text; // Use 'text' como o campo de exibição
                            },
                            templateSelection: function(repo) {
                                return repo.text; // Use 'text' como o campo de seleção
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
            <div class="form-group">
                <label for="id_produto" class="form-label">Produto:</label>
                {{ form.produto }}
            </div>
            
                 
            <div class="form-group">
                <label for="id_valor" class="form-label">Valor:</label>
                {{ form.valor }}
            </div>
            <div class="form-group">
                <label for="id_data_entrada" class="form-label">Data de Entrada:</label>
                {{ form.data_entrada }}
            </div>
            <div class="form-group">
                <label for="id_quantidade" class="form-label">Quantidade:</label>
                {{ form.quantidade }}
            </div>
            <div class="form-group">
                <label for="id_forma_recebimento" class="form-label">Forma de Recebimento:</label>
                {{ form.forma_recebimento }}
            </div>
            <div class="form-group">
                <label for="id_situacao" class="form-label">Situação:</label>
                {{ form.situacao }}
            </div>
            <div class="mb-3">
                {{ form.observacoes }}
            </div>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
    </div>
</div>
</div>
</div>

<script>
    $(document).ready(function() {
      // Inicializa o Datepicker no elemento com ID 'data-entrada'
      $('#data_entrada').datepicker({
          format: 'dd/mm/yyyy', // Define o formato da data
          language: 'pt-BR', // Define o idioma para português do Brasil
          autoclose: true, // Fecha o seletor de data ao selecionar uma data
          todayHighlight: true // Destaca a data atual
      });
  });
  

  </script>
{% endblock content %}

templates/agendaFinanceiraApp/financial_analysis.html
{% extends 'agendaFinanceiraApp/base2.html' %}

{% block content %}
<h1>Análise Financeira</h1>
<div>
    {{ df|safe }}
</div>
{% endblock %}